
#### REGISTER

GET http://localhost:5000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5YzU5M2ZmZWM3ZTZmYjFlMDhlNTgiLCJpYXQiOjE2OTA5NDUwNzd9.9J7JW78ra8ZWo3v-ur9xil9lyuYbhod1NNC5HiwJKYY


#### REGISTER

POST http://localhost:5000/api/auth/register
content-type: application/json

{
  "firstname": "hat",
  "lastname": "hat",
  "username": "hat",
  "password": "hat"
}

### LOGIN

POST http://localhost:5000/api/auth/login
content-type: application/json

{
  "username": "an",
  "password": "an"
}

### CREATE A NEW VIDEO

POST http://localhost:5000/api/video/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ1ZTRmODY0ODI3MTg1MTc1MDg0ZmEiLCJpYXQiOjE2OTE4MjU0MTV9.BY7Kvk4egaoIdcr25sTTvfb2Iq9jjOyIB2-vP7QId3M

{
  "video": "1.mp4",
  "language": "en",
  "noise": "deep",
  "summary": "lsa",
  "sentence": 2
}
### CREATE A NEW VIDEO SUBTITLE

POST http://localhost:5000/api/video/create/subtitle
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ1ZTRmODY0ODI3MTg1MTc1MDg0ZmEiLCJpYXQiOjE2OTE4MjU0MTV9.BY7Kvk4egaoIdcr25sTTvfb2Iq9jjOyIB2-vP7QId3M

{
  "video": "3.mp4",
  "sourceLanguage": "vi", 
  "targetLanguage": "vi",
  "algorithm": "noise"
}

### Get Videos All

GET http://localhost:5000/api/video/getallvideo/subtitle
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ1ZTRmODY0ODI3MTg1MTc1MDg0ZmEiLCJpYXQiOjE2OTE3MzkzODR9.LDAwHq0VLod4ihOH3mh3N66G-2E0FtODvjluFeJ5t00

### Get Videos All

GET http://localhost:5000/api/video/getallvideo/summary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ1ZTRmODY0ODI3MTg1MTc1MDg0ZmEiLCJpYXQiOjE2OTE3MzkzODR9.LDAwHq0VLod4ihOH3mh3N66G-2E0FtODvjluFeJ5t00

### Get video summary details
GET http://localhost:5000/api/video/get/summary/detail/20230818_025617
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ1ZTRmODY0ODI3MTg1MTc1MDg0ZmEiLCJpYXQiOjE2OTE3MzkzODR9.LDAwHq0VLod4ihOH3mh3N66G-2E0FtODvjluFeJ5t00

### Get video subtitle details
GET http://localhost:5000/api/video/get/subtitle/detail/20230818_035025
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ1ZTRmODY0ODI3MTg1MTc1MDg0ZmEiLCJpYXQiOjE2OTE3MzkzODR9.LDAwHq0VLod4ihOH3mh3N66G-2E0FtODvjluFeJ5t00
### FLASK API TEST SUMMARY

POST http://localhost:6000/api/createSummarize
Content-Type: application/json

{
  "video": "1.mp4",
  "language": "vi",
  "noise": "noise",
  "summary": "textrank",
  "sentence": 2
}


### FLASK API TEST SUBTITLE

POST http://localhost:6000/api/createSubtitle
Content-Type: application/json

{
  "video": "3.mp4",
  "sourceLanguage": "vi", 
  "targetLanguage": "vi",
  "algorithm": "noise"
}

### sdsfsfdsffds

POST http://localhost:5000/api/video/create/subtitle
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ1ZTRmODY0ODI3MTg1MTc1MDg0ZmEiLCJpYXQiOjE2OTE4MjU0MTV9.BY7Kvk4egaoIdcr25sTTvfb2Iq9jjOyIB2-vP7QId3M

{
  "video": "3.mp4",
  "sourceLanguage": "vi", 
  "targetLanguage": "vi",
  "algorithm": "noise"
}



### 19/1/2024  video, sourceLanguage, type, rate, volume, gender, adSubtitle
# "type": "google-cloud" hoac "openai-whisper"

POST http://localhost:5000/api/video/create/subtitle/v1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFhNzZmYTM5YzNkNDAwY2I5N2JhOGMiLCJpYXQiOjE3MDU2NzAzOTR9.qhov3mNQIlNsVezUfwe1evGZepAZ3P0Nxbzm7WNLnj0

{
  "video": "bbc.mp4",
  "type": "openai-whisper",
  "gender": "female",
  "adSubtitle": true
}

#### lấy ra toàn bộ video
GET http://localhost:5000/api/video/getallvideo/subtitle
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFhNzZmYTM5YzNkNDAwY2I5N2JhOGMiLCJpYXQiOjE3MDU2NzAzOTR9.qhov3mNQIlNsVezUfwe1evGZepAZ3P0Nxbzm7WNLnj0


#### lấy ra toàn bộ chi tiết 1 video
GET http://localhost:5000/api/video/get/subtitle/detail/20240119_150954
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFhNzZmYTM5YzNkNDAwY2I5N2JhOGMiLCJpYXQiOjE3MDU2NzAzOTR9.qhov3mNQIlNsVezUfwe1evGZepAZ3P0Nxbzm7WNLnj0




#####

GET http://localhost:5000/api/langauge/getall
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWFhNzZmYTM5YzNkNDAwY2I5N2JhOGMiLCJpYXQiOjE3MDU2NzAzOTR9.qhov3mNQIlNsVezUfwe1evGZepAZ3P0Nxbzm7WNLnj0
